function [A,b] = SelfBalancingCube_Acceleration(I,M,T_xb,T_yb,T_zb,d,g,phi,phi_dot,theta,theta_dot)
%SelfBalancingCube_Acceleration
%    [A,B] = SelfBalancingCube_Acceleration(I1_1,I1_2,I1_3,I2_1,I2_2,I2_3,I3_1,I3_2,I3_3,M,T_xb,T_yb,T_zb,D,G,PHI,PHI_DOT,THETA,THETA_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Jun-2023 11:53:35

I1_1 = I(1,1); I1_2 = I(1,2); I1_3 = I(1,3);
I2_1 = I(2,1); I2_2 = I(2,2); I2_3 = I(2,3);
I3_1 = I(3,1); I3_2 = I(3,2); I3_3 = I(3,3);

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = d.^2;
t7 = phi.*2.0;
t8 = phi_dot.^2;
t9 = theta_dot.^2;
t12 = sqrt(2.0);
t13 = sqrt(3.0);
t14 = sqrt(6.0);
t15 = I1_3./3.0;
t16 = I1_1./6.0;
t17 = I1_2./6.0;
t18 = I2_3./3.0;
t19 = I2_1./6.0;
t20 = I2_2./6.0;
t21 = I3_1./3.0;
t22 = I3_2./3.0;
t23 = I3_3./3.0;
t24 = I3_1./6.0;
t25 = I3_2./6.0;
t10 = t2.^2;
t11 = sin(t7);
t26 = -t15;
t27 = -t17;
t28 = -t18;
t29 = -t19;
t30 = -t20;
t31 = -t21;
t32 = -t22;
t33 = -t23;
t34 = -t25;
t35 = t16+t19+t24+t27+t30+t34;
t36 = t16+t17+t19+t20+t24+t25+t26+t28+t33;
mt1 = [I1_1.*(-1.0./3.0)-I1_2./3.0-I2_1./3.0-I2_2./3.0+t26+t28+t31+t32+t33-M.*t5.^2.*t6,I1_1.*t2.*t12.*(-1.0./6.0)-(I1_2.*t2.*t12)./6.0-(I1_3.*t2.*t12)./6.0+(I1_3.*t4.*t14)./6.0-(I2_1.*t2.*t12)./6.0-(I2_2.*t2.*t12)./6.0-(I2_3.*t2.*t12)./6.0-(I2_1.*t4.*t14)./6.0-(I2_2.*t4.*t14)./6.0-(I2_3.*t4.*t14)./6.0+t4.*t14.*t16+t2.*t12.*t21+t4.*t14.*t17+t2.*t12.*t22+t2.*t12.*t23,-t2.*t12.*t36+t4.*t14.*t35];
mt2 = [I1_1.*(-1.0./2.0)+I1_2./2.0+I2_1./2.0-I2_2./2.0+(I1_1.*t10)./3.0-I1_2.*t10.*(2.0./3.0)-I2_1.*t10.*(2.0./3.0)+(I2_2.*t10)./3.0-I3_3.*t10.*(2.0./3.0)-M.*t6+t10.*t15+t10.*t18+t10.*t21+t10.*t22-(I1_3.*t11.*t13)./6.0-(I2_2.*t11.*t13)./6.0+(I2_3.*t11.*t13)./6.0-(I3_1.*t11.*t13)./6.0+t11.*t13.*t16+t11.*t13.*t25];
A = reshape([mt1,mt2],2,2);
if nargout > 1
    et1 = t2.*theta_dot.*((t4.*theta_dot.*(I1_1-I1_2-I2_1+I2_2))./2.0-phi_dot.*t14.*(I1_3./6.0-I2_3./6.0+t16+t17+t29+t30)+t2.*t13.*theta_dot.*(t15-t16+t19+t20+t27+t28))-(T_xb.*t3.*t13)./3.0+(T_xb.*t5.*t12)./2.0-(T_yb.*t3.*t13)./3.0-(T_yb.*t5.*t12)./2.0-(T_zb.*t3.*t13)./3.0-t4.*theta_dot.*((phi_dot.*t12.*(I1_1.*3.0+I1_2.*3.0+I1_3.*3.0+I2_1.*3.0+I2_2.*3.0+I2_3.*3.0-I3_1.*6.0-I3_2.*6.0-I3_3.*6.0))./1.8e+1+t2.*theta_dot.*(I3_3.*(2.0./3.0)+t16+t17+t19+t20+t26+t28+t31+t32)-t4.*t13.*theta_dot.*(t16+t19+t22+t27+t30+t31))-M.*t2.*t5.*t6.*(t4.*t5.*t8+t4.*t5.*t9-phi_dot.*t2.*t3.*theta_dot.*2.0);
    et2 = M.*t4.*t5.*t6.*(t2.*t5.*t8+t2.*t5.*t9+phi_dot.*t3.*t4.*theta_dot.*2.0)-phi_dot.*t2.*t14.*t35.*theta_dot-phi_dot.*t4.*t12.*t36.*theta_dot;
    b = [et1+et2;T_xb.*t14.*(-1.0./6.0)-(T_yb.*t14)./6.0+(T_zb.*t14)./3.0+(I1_2.*phi_dot.*t13.*theta_dot)./3.0-(I1_3.*phi_dot.*t13.*theta_dot)./3.0-(I2_1.*phi_dot.*t13.*theta_dot)./3.0-(I3_2.*phi_dot.*t13.*theta_dot)./3.0+(I1_3.*t2.*t8.*t14)./6.0+(I1_3.*t4.*t8.*t12)./6.0-(I2_1.*t2.*t8.*t14)./6.0-(I2_2.*t2.*t8.*t14)./6.0-(I2_3.*t2.*t8.*t14)./6.0+(I2_3.*t4.*t8.*t12)./6.0-(I3_1.*t4.*t8.*t12)./3.0-(I3_2.*t4.*t8.*t12)./3.0-(I3_3.*t4.*t8.*t12)./3.0+phi_dot.*t13.*t18.*theta_dot+phi_dot.*t13.*t21.*theta_dot+t2.*t8.*t14.*t16+t4.*t8.*t12.*t16+t2.*t8.*t14.*t17+t4.*t8.*t12.*t17+t4.*t8.*t12.*t19+t4.*t8.*t12.*t20-(M.*t6.*t8.*sin(theta.*2.0))./2.0-M.*d.*g.*t5];
end
end
