function omega_dot = SelfBalancingCube_Acceleration(I,M,R,T_xb,T_yb,d,g,omega1,omega2,omega3,phi,phi_dot,phi_ddot,theta,theta_dot,theta_ddot)
%SelfBalancingCube_Acceleration
%    OMEGA_DOT = SelfBalancingCube_Acceleration(I1_1,I1_2,I1_3,I2_1,I2_2,I2_3,I3_1,I3_2,I3_3,M,R1_1,R1_2,R1_3,R2_1,R2_2,R2_3,R3_1,R3_2,R3_3,T_xb,T_yb,D,G,OMEGA1,OMEGA2,OMEGA3,PHI,PHI_DOT,PHI_DDOT,THETA,THETA_DOT,THETA_DDOT)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Jun-2023 13:06:17

I1_1 = I(1,1); I1_2 = I(1,2); I1_3 = I(1,3);
I2_1 = I(2,1); I2_2 = I(2,2); I2_3 = I(2,3);
I3_1 = I(3,1); I3_2 = I(3,2); I3_3 = R(3,3);

R1_1 = R(1,1); R1_2 = R(1,2); R1_3 = R(1,3);
R2_1 = R(2,1); R2_2 = R(2,2); R2_3 = R(2,3);
R3_1 = R(3,1); R3_2 = R(3,2); R3_3 = R(3,3);

t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = I1_1.^2;
t7 = I1_2.^2;
t8 = I1_3.^2;
t9 = I2_1.^2;
t10 = I2_2.^2;
t11 = I2_3.^2;
t12 = I3_1.^2;
t13 = I3_2.^2;
t14 = I3_3.^2;
t15 = d.^2;
t16 = omega1.^2;
t17 = omega2.^2;
t18 = omega3.^2;
t19 = phi_dot.^2;
t20 = theta.*2.0;
t22 = I1_1.*I2_2.*I3_3;
t23 = I1_1.*I2_3.*I3_2;
t24 = I1_2.*I2_1.*I3_3;
t25 = I1_2.*I2_3.*I3_1;
t26 = I1_3.*I2_1.*I3_2;
t27 = I1_3.*I2_2.*I3_1;
t21 = t3.^2;
t28 = sin(t20);
t29 = -t23;
t30 = -t24;
t31 = -t27;
t32 = t22+t25+t26+t29+t30+t31;
t33 = 1.0./t32;
et1 = I2_3.*t7.*t17+I2_3.*t13.*t17-I3_2.*t8.*t18-I3_2.*t11.*t18+I1_2.*I2_3.*R3_1.*T_xb-I1_2.*I3_3.*R2_1.*T_xb-I1_3.*I2_2.*R3_1.*T_xb+I1_3.*I3_2.*R2_1.*T_xb+I2_2.*I3_3.*R1_1.*T_xb-I2_3.*I3_2.*R1_1.*T_xb+I1_2.*I2_3.*R3_3.*T_xb-I1_2.*I3_3.*R2_3.*T_xb-I1_3.*I2_2.*R3_3.*T_xb+I1_3.*I3_2.*R2_3.*T_xb+I2_2.*I3_3.*R1_3.*T_xb-I2_3.*I3_2.*R1_3.*T_xb+I1_2.*I2_3.*R3_2.*T_yb-I1_2.*I3_3.*R2_2.*T_yb-I1_3.*I2_2.*R3_2.*T_yb+I1_3.*I3_2.*R2_2.*T_yb+I2_2.*I3_3.*R1_2.*T_yb-I2_3.*I3_2.*R1_2.*T_yb-I1_2.*I1_3.*I2_2.*t17-I1_2.*I2_1.*I2_3.*t16+I1_3.*I2_1.*I2_2.*t16+I1_2.*I1_3.*I3_3.*t18-I1_2.*I3_1.*I3_3.*t16+I1_3.*I3_1.*I3_2.*t16+I2_2.*I2_3.*I3_3.*t18-I2_2.*I3_2.*I3_3.*t17+I1_3.*omega1.*omega2.*t10-I1_2.*omega1.*omega3.*t11+I1_3.*omega1.*omega2.*t13-I1_2.*omega1.*omega3.*t14;
et2 = -I2_2.*omega2.*omega3.*t8-I2_2.*omega2.*omega3.*t14+I3_3.*omega2.*omega3.*t7+I3_3.*omega2.*omega3.*t10+I1_1.*I1_2.*I2_3.*omega1.*omega2-I1_1.*I1_3.*I2_2.*omega1.*omega2+I1_2.*I1_3.*I2_3.*omega2.*omega3+I1_1.*I1_2.*I3_3.*omega1.*omega3-I1_1.*I1_3.*I3_2.*omega1.*omega3-I1_2.*I2_2.*I2_3.*omega1.*omega2-I1_2.*I1_3.*I3_2.*omega2.*omega3+I1_3.*I2_2.*I2_3.*omega1.*omega3-I1_2.*I3_2.*I3_3.*omega1.*omega2+I2_1.*I2_2.*I3_3.*omega1.*omega3-I2_1.*I2_3.*I3_2.*omega1.*omega3+I1_3.*I3_2.*I3_3.*omega1.*omega3-I2_2.*I2_3.*I3_2.*omega2.*omega3-I2_2.*I3_1.*I3_3.*omega1.*omega2+I2_3.*I3_1.*I3_2.*omega1.*omega2+I2_3.*I3_2.*I3_3.*omega2.*omega3-I1_2.*I2_3.*M.*phi_ddot.*t15+I1_3.*I2_2.*M.*phi_ddot.*t15+I2_2.*I3_3.*M.*d.*g.*t3-I2_3.*I3_2.*M.*d.*g.*t3+I1_2.*I2_3.*M.*phi_ddot.*t15.*t21-I1_3.*I2_2.*M.*phi_ddot.*t15.*t21+I1_2.*I3_3.*M.*t2.*t15.*theta_ddot-I1_3.*I3_2.*M.*t2.*t15.*theta_ddot;
et3 = I2_2.*I3_3.*M.*t4.*t15.*theta_ddot-I2_3.*I3_2.*M.*t4.*t15.*theta_ddot-I1_2.*I2_3.*M.*phi_dot.*t15.*t28.*theta_dot+I1_3.*I2_2.*M.*phi_dot.*t15.*t28.*theta_dot-I1_2.*I2_3.*M.*d.*g.*t2.*t5+I1_3.*I2_2.*M.*d.*g.*t2.*t5-I1_2.*I3_3.*M.*phi_ddot.*t3.*t4.*t5.*t15+I1_3.*I3_2.*M.*phi_ddot.*t3.*t4.*t5.*t15+I2_2.*I3_3.*M.*phi_ddot.*t2.*t3.*t5.*t15-I2_3.*I3_2.*M.*phi_ddot.*t2.*t3.*t5.*t15-I1_2.*I3_3.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I1_3.*I3_2.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I2_2.*I3_3.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I2_3.*I3_2.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I1_2.*I3_3.*M.*t2.*t3.*t5.*t15.*t19+I1_3.*I3_2.*M.*t2.*t3.*t5.*t15.*t19-I2_2.*I3_3.*M.*t3.*t4.*t5.*t15.*t19+I2_3.*I3_2.*M.*t3.*t4.*t5.*t15.*t19;
et4 = I1_3.*t9.*t16+I1_3.*t12.*t16-I3_1.*t8.*t18-I3_1.*t11.*t18+I1_1.*I2_3.*R3_1.*T_xb-I1_1.*I3_3.*R2_1.*T_xb-I1_3.*I2_1.*R3_1.*T_xb+I1_3.*I3_1.*R2_1.*T_xb+I2_1.*I3_3.*R1_1.*T_xb-I2_3.*I3_1.*R1_1.*T_xb+I1_1.*I2_3.*R3_3.*T_xb-I1_1.*I3_3.*R2_3.*T_xb-I1_3.*I2_1.*R3_3.*T_xb+I1_3.*I3_1.*R2_3.*T_xb+I2_1.*I3_3.*R1_3.*T_xb-I2_3.*I3_1.*R1_3.*T_xb+I1_1.*I2_3.*R3_2.*T_yb-I1_1.*I3_3.*R2_2.*T_yb-I1_3.*I2_1.*R3_2.*T_yb+I1_3.*I3_1.*R2_2.*T_yb+I2_1.*I3_3.*R1_2.*T_yb-I2_3.*I3_1.*R1_2.*T_yb+I1_1.*I1_2.*I2_3.*t17-I1_2.*I1_3.*I2_1.*t17-I1_1.*I2_1.*I2_3.*t16+I1_1.*I1_3.*I3_3.*t18-I1_1.*I3_1.*I3_3.*t16+I2_1.*I2_3.*I3_3.*t18-I2_1.*I3_2.*I3_3.*t17+I2_3.*I3_1.*I3_2.*t17-I1_1.*omega1.*omega3.*t11-I1_1.*omega1.*omega3.*t14+I2_3.*omega1.*omega2.*t6;
et5 = -I2_1.*omega2.*omega3.*t8+I2_3.*omega1.*omega2.*t12-I2_1.*omega2.*omega3.*t14+I3_3.*omega1.*omega3.*t6+I3_3.*omega1.*omega3.*t9-I1_1.*I1_3.*I2_1.*omega1.*omega2+I1_1.*I1_3.*I2_3.*omega2.*omega3-I1_1.*I1_3.*I3_1.*omega1.*omega3-I1_1.*I2_2.*I2_3.*omega1.*omega2+I1_3.*I2_1.*I2_2.*omega1.*omega2+I1_1.*I1_2.*I3_3.*omega2.*omega3-I1_2.*I1_3.*I3_1.*omega2.*omega3+I1_3.*I2_1.*I2_3.*omega1.*omega3-I1_1.*I3_2.*I3_3.*omega1.*omega2+I1_3.*I3_1.*I3_2.*omega1.*omega2-I2_1.*I2_3.*I3_1.*omega1.*omega3+I1_3.*I3_1.*I3_3.*omega1.*omega3+I2_1.*I2_2.*I3_3.*omega2.*omega3-I2_2.*I2_3.*I3_1.*omega2.*omega3-I2_1.*I3_1.*I3_3.*omega1.*omega2+I2_3.*I3_1.*I3_3.*omega2.*omega3-I1_1.*I2_3.*M.*phi_ddot.*t15+I1_3.*I2_1.*M.*phi_ddot.*t15+I2_1.*I3_3.*M.*d.*g.*t3-I2_3.*I3_1.*M.*d.*g.*t3+I1_1.*I2_3.*M.*phi_ddot.*t15.*t21-I1_3.*I2_1.*M.*phi_ddot.*t15.*t21+I1_1.*I3_3.*M.*t2.*t15.*theta_ddot;
et6 = -I1_3.*I3_1.*M.*t2.*t15.*theta_ddot+I2_1.*I3_3.*M.*t4.*t15.*theta_ddot-I2_3.*I3_1.*M.*t4.*t15.*theta_ddot-I1_1.*I2_3.*M.*phi_dot.*t15.*t28.*theta_dot+I1_3.*I2_1.*M.*phi_dot.*t15.*t28.*theta_dot-I1_1.*I2_3.*M.*d.*g.*t2.*t5+I1_3.*I2_1.*M.*d.*g.*t2.*t5-I1_1.*I3_3.*M.*phi_ddot.*t3.*t4.*t5.*t15+I1_3.*I3_1.*M.*phi_ddot.*t3.*t4.*t5.*t15+I2_1.*I3_3.*M.*phi_ddot.*t2.*t3.*t5.*t15-I2_3.*I3_1.*M.*phi_ddot.*t2.*t3.*t5.*t15-I1_1.*I3_3.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I1_3.*I3_1.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I2_1.*I3_3.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I2_3.*I3_1.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I1_1.*I3_3.*M.*t2.*t3.*t5.*t15.*t19+I1_3.*I3_1.*M.*t2.*t3.*t5.*t15.*t19-I2_1.*I3_3.*M.*t3.*t4.*t5.*t15.*t19+I2_3.*I3_1.*M.*t3.*t4.*t5.*t15.*t19;
et7 = I1_2.*t9.*t16+I1_2.*t12.*t16-I2_1.*t7.*t17-I2_1.*t13.*t17+I1_1.*I2_2.*R3_1.*T_xb-I1_1.*I3_2.*R2_1.*T_xb-I1_2.*I2_1.*R3_1.*T_xb+I1_2.*I3_1.*R2_1.*T_xb+I2_1.*I3_2.*R1_1.*T_xb-I2_2.*I3_1.*R1_1.*T_xb+I1_1.*I2_2.*R3_3.*T_xb-I1_1.*I3_2.*R2_3.*T_xb-I1_2.*I2_1.*R3_3.*T_xb+I1_2.*I3_1.*R2_3.*T_xb+I2_1.*I3_2.*R1_3.*T_xb-I2_2.*I3_1.*R1_3.*T_xb+I1_1.*I2_2.*R3_2.*T_yb-I1_1.*I3_2.*R2_2.*T_yb-I1_2.*I2_1.*R3_2.*T_yb+I1_2.*I3_1.*R2_2.*T_yb+I2_1.*I3_2.*R1_2.*T_yb-I2_2.*I3_1.*R1_2.*T_yb+I1_1.*I1_2.*I2_2.*t17-I1_1.*I2_1.*I2_2.*t16+I1_1.*I1_3.*I3_2.*t18-I1_2.*I1_3.*I3_1.*t18-I1_1.*I3_1.*I3_2.*t16+I2_1.*I2_3.*I3_2.*t18-I2_2.*I2_3.*I3_1.*t18+I2_2.*I3_1.*I3_2.*t17-I1_1.*omega1.*omega2.*t10-I1_1.*omega1.*omega2.*t13+I2_2.*omega1.*omega2.*t6+I2_2.*omega1.*omega2.*t12;
et8 = I3_2.*omega1.*omega3.*t6-I3_1.*omega2.*omega3.*t7+I3_2.*omega1.*omega3.*t9-I3_1.*omega2.*omega3.*t10-I1_1.*I1_2.*I2_1.*omega1.*omega2+I1_1.*I1_3.*I2_2.*omega2.*omega3-I1_2.*I1_3.*I2_1.*omega2.*omega3-I1_1.*I1_2.*I3_1.*omega1.*omega3+I1_2.*I2_1.*I2_2.*omega1.*omega2+I1_1.*I1_2.*I3_2.*omega2.*omega3-I1_1.*I2_2.*I2_3.*omega1.*omega3+I1_2.*I2_1.*I2_3.*omega1.*omega3+I1_2.*I3_1.*I3_2.*omega1.*omega2-I2_1.*I2_2.*I3_1.*omega1.*omega3-I1_1.*I3_2.*I3_3.*omega1.*omega3+I1_2.*I3_1.*I3_3.*omega1.*omega3+I2_1.*I2_2.*I3_2.*omega2.*omega3-I2_1.*I3_1.*I3_2.*omega1.*omega2-I2_1.*I3_2.*I3_3.*omega2.*omega3+I2_2.*I3_1.*I3_3.*omega2.*omega3-I1_1.*I2_2.*M.*phi_ddot.*t15+I1_2.*I2_1.*M.*phi_ddot.*t15+I2_1.*I3_2.*M.*d.*g.*t3-I2_2.*I3_1.*M.*d.*g.*t3+I1_1.*I2_2.*M.*phi_ddot.*t15.*t21-I1_2.*I2_1.*M.*phi_ddot.*t15.*t21+I1_1.*I3_2.*M.*t2.*t15.*theta_ddot-I1_2.*I3_1.*M.*t2.*t15.*theta_ddot;
et9 = I2_1.*I3_2.*M.*t4.*t15.*theta_ddot-I2_2.*I3_1.*M.*t4.*t15.*theta_ddot-I1_1.*I2_2.*M.*phi_dot.*t15.*t28.*theta_dot+I1_2.*I2_1.*M.*phi_dot.*t15.*t28.*theta_dot-I1_1.*I2_2.*M.*d.*g.*t2.*t5+I1_2.*I2_1.*M.*d.*g.*t2.*t5-I1_1.*I3_2.*M.*phi_ddot.*t3.*t4.*t5.*t15+I1_2.*I3_1.*M.*phi_ddot.*t3.*t4.*t5.*t15+I2_1.*I3_2.*M.*phi_ddot.*t2.*t3.*t5.*t15-I2_2.*I3_1.*M.*phi_ddot.*t2.*t3.*t5.*t15-I1_1.*I3_2.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I1_2.*I3_1.*M.*phi_dot.*t4.*t15.*t21.*theta_dot.*2.0+I2_1.*I3_2.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I2_2.*I3_1.*M.*phi_dot.*t2.*t15.*t21.*theta_dot.*2.0-I1_1.*I3_2.*M.*t2.*t3.*t5.*t15.*t19+I1_2.*I3_1.*M.*t2.*t3.*t5.*t15.*t19-I2_1.*I3_2.*M.*t3.*t4.*t5.*t15.*t19+I2_2.*I3_1.*M.*t3.*t4.*t5.*t15.*t19;
omega_dot = [t33.*(et1+et2+et3);-t33.*(et4+et5+et6);t33.*(et7+et8+et9)];
end
